allow_empty_prefix: false
api_root_path: ''
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
db_connection_str: '**********'
db_permissions:
- '*.*:rw'
db_prefix: test_
docs_url: /docs
generate_correlation_id: true
host: 127.0.0.1
kafka_max_message_size: 1048576
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
log_traceback: true
object_storages:
  primary:
    bucket: permanent
    credentials:
      aws_config_ini: null
      s3_access_key_id: test
      s3_endpoint_url: http://localstack:4566
      s3_secret_access_key: '**********'
      s3_session_token: null
  secondary:
    bucket: staging
    credentials:
      aws_config_ini: null
      s3_access_key_id: test
      s3_endpoint_url: http://localstack:4566
      s3_secret_access_key: '**********'
      s3_session_token: null
openapi_url: /openapi.json
port: 8080
service_instance_id: '1'
service_name: sms
token_hashes:
- 7ad83b6b9183c91674eec897935bc154ba9ff9704f8be0840e77f476b5062b6e
vault_path: ekss
vault_token: dev-token
vault_url: http://vault:8200
workers: 1
