components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    UpsertionDetails:
      description: Details for upserting documents in a collection.
      properties:
        documents:
          anyOf:
          - type: object
          - items:
              type: object
            type: array
          description: The document(s) to upsert.
          title: Documents
        id_field:
          default: _id
          description: The field to use as the document id.
          title: Id Field
          type: string
      required:
      - documents
      title: UpsertionDetails
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
  securitySchemes:
    HTTPBearer:
      scheme: bearer
      type: http
info:
  description: A service for basic infrastructure technology state management.
  title: State Management Service
  version: 1.0.0
openapi: 3.1.0
paths:
  /documents/permissions:
    get:
      description: Returns the configured db permissions list.
      operationId: get_configured_permissions_documents_permissions_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  type: string
                title: Response Get Configured Permissions Documents Permissions Get
                type: array
          description: Successful Response
      summary: Returns the configured db permissions list.
      tags:
      - StateManagementService
      - sms-mongodb
  /documents/{db_name}/{collection}:
    delete:
      description: Upserts the document(s) provided in the request body in the specified
        collection.
      operationId: delete_docs_documents__db_name___collection__delete
      parameters:
      - in: path
        name: db_name
        required: true
        schema:
          title: Db Name
          type: string
      - in: path
        name: collection
        required: true
        schema:
          title: Collection
          type: string
      responses:
        '204':
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - HTTPBearer: []
      summary: Deletes all or some documents in the collection.
      tags:
      - StateManagementService
      - sms-mongodb
    get:
      description: Returns all or some documents from the specified collection.
      operationId: get_docs_documents__db_name___collection__get
      parameters:
      - in: path
        name: db_name
        required: true
        schema:
          title: Db Name
          type: string
      - in: path
        name: collection
        required: true
        schema:
          title: Collection
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  type: object
                title: Response Get Docs Documents  Db Name   Collection  Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - HTTPBearer: []
      summary: Returns all or some documents from the specified collection.
      tags:
      - StateManagementService
      - sms-mongodb
    put:
      description: Upserts the document(s) provided in the request body in the specified
        collection.
      operationId: upsert_docs_documents__db_name___collection__put
      parameters:
      - in: path
        name: db_name
        required: true
        schema:
          title: Db Name
          type: string
      - in: path
        name: collection
        required: true
        schema:
          title: Collection
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertionDetails'
        required: true
      responses:
        '204':
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - HTTPBearer: []
      summary: Upserts the document(s) provided in the request body in thespecified
        collection.
      tags:
      - StateManagementService
      - sms-mongodb
  /health:
    get:
      description: Used to test if this service is alive
      operationId: health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: health
      tags:
      - StateManagementService
      - sms-
tags:
- name: StateManagementService
