[project]
name = "sms"
version = "5.0.0"
description = "State Management Service - Provides a REST API for basic infrastructure technology state management."
dependencies = [
    "typer >= 0.25",
    "ghga-service-commons[api] >= 7.0",
    "hexkit[mongodb,s3,akafka] >= 8.1",
    "hvac>=2",
]

[project.urls]
Repository = "https://github.com/ghga-de/state-management-service"

[project.scripts]
sms = "sms.__main__:run"
