[project]
name = "sms"
version = "0.1.0"
description = "State Management Service - Provides a REST API for basic infrastructure technology state management."
dependencies = [
    "typer >= 0.12",
    "ghga-service-commons[api] >= 3.1",
    "hexkit[mongodb] >= 3.2",
]

[project.urls]
Repository = "https://github.com/ghga-de/state-management-service"

[project.scripts]
sms = "sms.__main__:run"
