[project]
name = "sms"
version = "4.0.2"
description = "State Management Service - Provides a REST API for basic infrastructure technology state management."
dependencies = [
    "typer >= 0.12",
    "ghga-service-commons[api] >= 4.1",
    "hexkit[mongodb,s3,akafka] >= 5.1",
    "hvac>=2",
]

[project.urls]
Repository = "https://github.com/ghga-de/state-management-service"

[project.scripts]
sms = "sms.__main__:run"
